"""F2 "Endless Ops" — the procedural-mission half of F2 (docs/3.0-PROGRESS.md §F2's "lebendige Wirtschaft,
Endlos-Ops, Teams, Basis" bundle). Scope decision (user-approved, 2026-10-04, see §F2's progress-doc note): F2 as a
whole is a large, still-partly-undefined feature; this module builds the one piece Act VIII actually needs per
docs/story/02-acts-and-levels.md — "chained scripts, endless-ops-style procedural missions" — as a real, reusable
system, not a placeholder. The base/economy/teams pieces of F2 remain out of scope here (same cut order the user set
originally: "wenn es zu viel wird: zuerst Teams streichen, dann Endlos-Ops, dann Basis" — this module *is* the
Endlos-Ops slice, built because Act VIII specifically calls for it).

Design: an "endless op" is an ordinary ``Mission`` built at call time from a deterministic seed, using the exact
same ``Mission``/``Objective``/``MissionRunner``/solver machinery as every hand-authored mission — nothing new to
test or maintain on the engine side. A ``Template`` describes one archetype (recon, incident response, file
forensics, a Windows audit, a defense watch); ``generate_endless_mission`` picks a template and seeds a fresh world
from it, registering a uniquely-named scenario the same way ``generators.py``'s C2-era Mini generators already do.
``generate_endless_chain`` strings several of these together with ascending ``requires`` and a small per-step reward
bump, matching "endless ops" in the literal sense (no fixed end — stop whenever you want, each step a little harder
than the last) and "chained scripts" (the framing the player experiences, not a literal shell script file).

Same seed -> same mission, always (ties into the existing F1 backlog item "daily challenge with seed", and into C7's
"after level 200, missions replayable" — an endless op replayed is a *different*, but still solvable, instance,
exactly like a Mini generated by ``generators.py``).
"""
from __future__ import annotations

import random
from dataclasses import dataclass
from typing import Callable

from ..shell.fs import User, VFS
from ..shell.machine import Machine, Process, Service, Session, World
from .mission import Mission, Objective
from .scenarios import EPOCH, scenario

HOSTNAMES = ["EDGE-NODE", "RELAY-STATION", "GATEWAY-HOST", "PROXY-NINE", "NODE-CACHE", "SHADOW-RELAY", "OUTPOST-DELTA"]
FLAGGED_WORDS = ["STAGING-OVERRIDE", "UNLISTED-BUILD", "INTERNAL-ONLY", "DO-NOT-PUBLISH", "LEGACY-BACKDOOR"]
ROGUE_PROC_NAMES = ["cryptotool", "sys-helper", "netwatch", "svc-ghost", "resolvd"]
BACKUP_NAMES = ["nightly.cfg", "ledger.bak", "snapshot.dat", "export.cfg", "vault.bak"]
WIN_HOSTNAMES = ["BRANCH-01", "KIOSK-07", "FILESRV-02", "PRINT-HOST", "ADMIN-BOX"]


def _op_rig(home: dict | None = None) -> Machine:
    m = Machine("home", "home-rig", "10.44.0.7", "linux", VFS("posix", clock=lambda: EPOCH))
    m.fs.load({"home": {"operator": {"_owner": "operator", "_group": "operator", **(home or {})}}})
    m.add_user(User("root", 0, 0, ("root",), "/root", admin=True, password="toor"))
    m.add_user(User("operator", 1000, 1000, ("operator",), "/home/operator", password="hunter2"))
    m.data["sudoers"] = {"operator": {"commands": "ALL", "nopasswd": True}}
    return m


def _rand_ip(rng: random.Random, prefix: str = "203.0.113") -> str:
    return f"{prefix}.{rng.randint(10, 250)}"


@dataclass
class EndlessInstance:
    build_world: Callable[[], tuple[World, Session]]
    objectives: list[Objective]
    solution: list[str]
    briefing: list[str]
    debrief: list[str]
    title: str
    base_xp: int
    tags: list[str]


def _tpl_recon_sweep(rng: random.Random) -> EndlessInstance:
    ip = _rand_ip(rng)
    host = rng.choice(HOSTNAMES) + f"-{rng.randint(10, 99)}"
    word = rng.choice(FLAGGED_WORDS)
    url = f"http://{ip}/"

    def build() -> tuple[World, Session]:
        world = World(clock=lambda: EPOCH)
        player = _op_rig({"notes.txt": f"MIRA: New contract came in overnight — sweep {host} ({ip}) and see what "
                                       "its banner actually says.\n"})
        target = Machine(host, host, ip, "linux", VFS("posix", clock=lambda: EPOCH))
        target.add_user(User("admin", 1000, 1000, ("admin",), "/home/admin", password="changeme"))
        target.services = [Service(80, "http", f"nginx — X-Build: {word}", "open")]
        world.add(player)
        world.add(target)
        player.neighbors.append(target.id)
        return world, Session(player, player.users["operator"], "bash")

    return EndlessInstance(
        build_world=build,
        objectives=[Objective(event="command", match={"name": "curl", "args__contains": url, "status": 0}, text=f"Grab {host}'s banner (curl -I)",
                              hints=["curl -I fetches just the headers.", f"Try: curl -I {url}", f"curl -I {url}"])],
        solution=[f"curl -I {url}"],
        briefing=[f"MIRA: New contract came in overnight — sweep {host} ({ip}) and see what its banner says."],
        debrief=[f"MIRA: '{word}.' Someone's build label leaking in plain sight. Noted, filed, next one."],
        title=f"Sweep: {host}", base_xp=60, tags=["endless", "recon", "curl"],
    )


def _tpl_incident_response(rng: random.Random) -> EndlessInstance:
    name = rng.choice(ROGUE_PROC_NAMES)
    pid = rng.randint(2000, 9000)
    cpu = round(rng.uniform(40.0, 95.0), 1)

    def build() -> tuple[World, Session]:
        world = World(clock=lambda: EPOCH)
        m = _op_rig({"notes.txt": "NEXUS: Something's eating CPU again. Same routine as always.\n"})
        m.processes.append(Process(pid=pid, user="operator", name=name, cmd=f"/tmp/.cache/{name} --daemon", cpu=cpu, mem=2.5))
        world.add(m)
        return world, Session(m, m.users["operator"], "bash")

    return EndlessInstance(
        build_world=build,
        objectives=[
            Objective(event="command", match={"name": "ps", "status": 0}, text="Check what's running (ps aux)",
                     hints=["ps aux lists every process.", "Try: ps aux", "ps aux"]),
            Objective(event="process_killed", match={"pid": pid}, text=f"Stop it (kill {pid})",
                     hints=["kill PID stops a process by number.", f"Try: kill {pid}", f"kill {pid}"]),
        ],
        solution=["ps aux", f"kill {pid}"],
        briefing=["NEXUS: Something's eating CPU again. Same routine as always."],
        debrief=[f"NEXUS: '{name}.' Gone. These never stop showing up, but at least they're never interesting."],
        title=f"Contain: {name}", base_xp=70, tags=["endless", "incident", "ps", "kill"],
    )


def _tpl_file_forensics(rng: random.Random) -> EndlessInstance:
    good_name = rng.choice(BACKUP_NAMES)
    bad_name = rng.choice([n for n in BACKUP_NAMES if n != good_name])
    good_content = f"state=stable\nchecksum-seed={rng.randint(1000, 9999)}\n"
    bad_content = f"state=stable\nchecksum-seed={rng.randint(1000, 9999)}\ntampered=true\n"
    import hashlib
    manifest = f"{hashlib.md5(good_content.encode()).hexdigest()}  {good_name}\n{hashlib.md5(b'placeholder').hexdigest()}  {bad_name}\n"

    def build() -> tuple[World, Session]:
        world = World(clock=lambda: EPOCH)
        m = _op_rig({"backups": {good_name: good_content, bad_name: bad_content, "manifest.md5": manifest},
                     "notes.txt": "MIRA: Verify this backup set against its manifest before anyone trusts it.\n"})
        world.add(m)
        return world, Session(m, m.users["operator"], "bash")

    return EndlessInstance(
        build_world=build,
        objectives=[Objective(event="command", match={"name": "md5sum", "args__contains": "-c", "status": 1}, text="Verify the backup set (md5sum -c)",
                              hints=["md5sum -c checks files against a manifest — run it from the right folder.",
                                    "Try: cd backups, then md5sum -c manifest.md5", "cd backups\nmd5sum -c manifest.md5"])],
        solution=["cd backups", "md5sum -c manifest.md5"],
        briefing=["MIRA: Verify this backup set against its manifest before anyone trusts it."],
        debrief=[f"MIRA: '{bad_name}' doesn't match. Good catch — that's exactly why we check."],
        title="Verify the Set", base_xp=65, tags=["endless", "forensics", "md5sum"],
    )


def _tpl_windows_audit(rng: random.Random) -> EndlessInstance:
    host = rng.choice(WIN_HOSTNAMES) + f"-{rng.randint(10, 99)}"
    ip = f"10.60.{rng.randint(0, 9)}.{rng.randint(10, 250)}"
    user, pw = "svcops", f"Audit-{rng.randint(1000, 9999)}!"

    def build() -> tuple[World, Session]:
        world = World(clock=lambda: EPOCH)
        player = _op_rig({"notes.txt": f"MIRA: Quick audit on {host} — anything stopped that shouldn't be.\n"})
        target = Machine(host, host, ip, "windows", VFS("windows", clock=lambda: EPOCH))
        target.add_user(User(user, 1000, 1000, ("Administrators",), f"C:\\Users\\{user}", password=pw))
        target.services = [Service(22, "ssh", "OpenSSH for Windows 9.6", "open")]
        target.data["winservices"] = [{"Status": "Running", "Name": "Spooler", "DisplayName": "Print Spooler"},
                                      {"Status": "Stopped", "Name": "wuauserv", "DisplayName": "Windows Update"}]
        world.add(player)
        world.add(target)
        player.neighbors.append(target.id)
        return world, Session(player, player.users["operator"], "bash")

    return EndlessInstance(
        build_world=build,
        objectives=[Objective(event="command", match={"name": "Where-Object", "status": 0}, text="Find stopped services (Where-Object)",
                              hints=["Get-Service | Where-Object Status -eq Stopped filters for stopped services.",
                                    f"Try: sshpass -p {pw} ssh {user}@{ip}, then Get-Service | Where-Object Status -eq Stopped",
                                    f"sshpass -p {pw} ssh {user}@{ip}\nGet-Service | Where-Object Status -eq Stopped"])],
        solution=[f"sshpass -p {pw} ssh {user}@{ip}", "Get-Service | Where-Object Status -eq Stopped"],
        briefing=[f"MIRA: Quick audit on {host} — anything stopped that shouldn't be."],
        debrief=["MIRA: wuauserv, stopped, same as half these boxes. Flagged, moving on."],
        title=f"Audit: {host}", base_xp=75, tags=["endless", "windows", "where-object"],
    )


def _tpl_defense_watch(rng: random.Random) -> EndlessInstance:
    intruder_ip = _rand_ip(rng, prefix=f"198.51.{rng.randint(100, 200)}")
    host = "WATCH-" + str(rng.randint(100, 999))
    edge_ip = f"198.51.100.{rng.randint(10, 99)}"
    log = [f"{rng.randint(10,23):02d}:{rng.randint(0,59):02d}:{rng.randint(0,59):02d} svc[auth]: failed login for root from {intruder_ip}",
          f"{rng.randint(10,23):02d}:{rng.randint(0,59):02d}:{rng.randint(0,59):02d} svc[auth]: failed login for root from {intruder_ip}"]

    def build() -> tuple[World, Session]:
        world = World(clock=lambda: EPOCH)
        player = _op_rig({"notes.txt": f"ODUYA: {host} is on the rotation now too. Same watch, same habits.\n"})
        edge = Machine(host, host, edge_ip, "linux", VFS("posix", clock=lambda: EPOCH))
        edge.add_user(User("operator", 1000, 1000, ("operator",), "/home/operator", password="hunter2"))
        edge.fs.load({"var": {"log": {"auth.log": log}}, "home": {"operator": {"_owner": "operator", "_group": "operator"}}})
        edge.services = [Service(22, "ssh", "OpenSSH 9.6", "open")]
        world.add(player)
        world.add(edge)
        player.neighbors.append(edge.id)
        return world, Session(player, player.users["operator"], "bash")

    return EndlessInstance(
        build_world=build,
        objectives=[
            Objective(event="command", match={"name": "grep", "args__contains": "failed", "status": 0}, text="Check the log (grep failed)",
                     hints=["Same first habit as always.", "Try: grep failed /var/log/auth.log", "grep failed /var/log/auth.log"]),
            Objective(event="command", match={"name": "echo", "args__contains": intruder_ip, "status": 0}, text="Add it to the blocklist",
                     hints=["Same file-based blocklist as EDGE-RELAY.", f"Try: echo {intruder_ip} >> firewall_rules.conf", f"echo {intruder_ip} >> firewall_rules.conf"]),
        ],
        solution=[f"sshpass -p hunter2 ssh operator@{edge_ip}", "grep failed /var/log/auth.log", f"echo {intruder_ip} >> firewall_rules.conf"],
        briefing=[f"ODUYA: {host} is on the rotation now too. Same watch, same habits."],
        debrief=[f"ODUYA: {intruder_ip}, blocked. One more box covered."],
        title=f"Watch: {host}", base_xp=70, tags=["endless", "defense", "grep"],
    )


_SEEN_MISSION_IDS: set[str] = set()

TEMPLATES: dict[str, Callable[[random.Random], EndlessInstance]] = {
    "recon_sweep": _tpl_recon_sweep,
    "incident_response": _tpl_incident_response,
    "file_forensics": _tpl_file_forensics,
    "windows_audit": _tpl_windows_audit,
    "defense_watch": _tpl_defense_watch,
}


def generate_endless_mission(mission_id: str, number: int, act: int, seed: int, template_key: str | None = None,
                             requires: list[str] | None = None, difficulty: float = 1.0) -> Mission:
    """Build one procedurally-generated mission from ``seed``. Same seed and template -> same mission, always.
    ``difficulty`` scales the reward (used by ``generate_endless_chain`` for an ascending "ops queue")."""
    if mission_id in _SEEN_MISSION_IDS:
        raise ValueError(f"generate_endless_mission: mission_id {mission_id!r} was already used — scenario "
                         "registration is keyed by mission_id, so a repeat silently overwrites the earlier "
                         "mission's world in SCENARIOS. Give every call (including across different "
                         "generate_endless_chain calls) a globally unique id.")
    _SEEN_MISSION_IDS.add(mission_id)
    rng = random.Random(seed)
    key = template_key or rng.choice(list(TEMPLATES))
    instance = TEMPLATES[key](rng)
    scenario_name = f"endless_{mission_id}"
    scenario(scenario_name)(instance.build_world)
    return Mission(
        id=mission_id, number=number, act=act, size="mini" if len(instance.objectives) == 1 else "standard",
        title=instance.title, scenario=scenario_name, requires=requires or [],
        briefing=instance.briefing, debrief=instance.debrief, objectives=instance.objectives,
        solution=instance.solution, reward_xp=round(instance.base_xp * difficulty), tags=[*instance.tags, "f2"],
    )


def generate_endless_chain(start_id: str, start_number: int, act: int, seed: int, length: int,
                           requires_first: list[str] | None = None, template_keys: list[str] | None = None) -> list[Mission]:
    """A run of ``length`` endless ops chained by ``requires``, each a little harder than the last — "endless ops"
    in the literal sense (no fixed end to the archetype; a real campaign spot just calls for a finite slice of it),
    and "chained scripts" in the framing Act VIII's design calls for."""
    missions: list[Mission] = []
    prev_req = requires_first or []
    for i in range(length):
        key = template_keys[i % len(template_keys)] if template_keys else None
        mid = f"{start_id}_{i}"
        m = generate_endless_mission(mid, start_number + i, act, seed * 100 + i, template_key=key,
                                     requires=prev_req, difficulty=1.0 + 0.15 * i)
        missions.append(m)
        prev_req = [mid]
    return missions
