"""Hand-written flavour and structure for the generated side missions (see build_content.py)."""

# ---------------------------------------------------------------- servers --
SERVERS = {
    "harbor": dict(name="HARBOR", ip="10.42.40.11", region="PORT", pos=[0.13, 0.27], security="MEDIUM", fw=None, routing=None,
                   user="dockhand", pw="crane-41", links=["polaris", "nexus_grid"],
                   desc="Freight logistics for the eastern docks. Every crate has a record. Some records are lies.",
                   motd=["HARBOR // FREIGHT LOGISTICS", "Cranes online: 14. Questions answered: 0."]),
    "lumen": dict(name="LUMEN", ip="10.42.41.3", region="POWER", pos=[0.37, 0.08], security="MEDIUM", fw=dict(level=1, symbols=6, length=4, attempts=6, label="LUMEN-GATE"),
                  routing=None, user="grid_tech", pw="ohm-law", links=["polaris", "blackvault"],
                  desc="Regional power utility. Keeps the lights on and a lot of secrets lit.",
                  motd=["LUMEN // POWER UTILITY", "Load: nominal. Morale: not."]),
    "tidal": dict(name="TIDAL", ip="10.42.42.9", region="TELECOM", pos=[0.22, 0.70], security="MEDIUM", fw=None, routing=None,
                  user="line_ops", pw="wave-9", links=["relay_7", "echo"],
                  desc="Telecom backbone. Everything that moves through the city passes through TIDAL.",
                  motd=["TIDAL // TELECOM BACKBONE", "Latency: 11ms. Eavesdroppers: unknown."],
                  trace=dict(hits=5, misses=3, speed=1.0, decoys=6, level=1, title="BACKBONE TRAFFIC")),
    "sable": dict(name="SABLE", ip="10.42.43.17", region="FINANCE", pos=[0.50, 0.52], security="HIGH", fw=dict(level=1, symbols=6, length=4, attempts=6, label="SABLE-VAULT"),
                  routing=1, user="teller", pw="gold-bar-3", links=["nexus_grid", "helix"],
                  desc="A private bank for people who do not appear in bank records.",
                  motd=["SABLE // PRIVATE BANK", "Discretion is our only product."]),
    "foundry": dict(name="FOUNDRY", ip="10.42.44.2", region="INDUSTRY", pos=[0.35, 0.62], security="HIGH", fw=dict(level=2, symbols=6, length=5, attempts=7, label="FOUNDRY-WALL"),
                    routing=None, user="smith", pw="anvil-7", links=["relay_7", "sable"],
                    desc="Automated heavy industry. Robots do the work; NEXUS does the thinking.",
                    motd=["FOUNDRY // AUTOMATED INDUSTRY", "Shift 3 running. No humans on site."]),
    "orchard": dict(name="ORCHARD", ip="10.42.45.31", region="BIOTECH", pos=[0.70, 0.18], security="HIGH", fw=dict(level=2, symbols=6, length=5, attempts=7, label="ORCHARD-SHIELD"),
                    routing=None, user="agro", pw="seed-bank", links=["archive_9", "ghostnet"],
                    desc="Agricultural biotech. The crops are fine. The research notes are not.",
                    motd=["ORCHARD // AGRI-BIOTECH", "Growth cycle 41. Anomalies: classified."]),
    "atlas": dict(name="ATLAS", ip="10.42.46.8", region="SURVEY", pos=[0.72, 0.80], security="CRITICAL", fw=dict(level=3, symbols=7, length=5, attempts=7, label="ATLAS-AEGIS"),
                  routing=2, user="surveyor", pw="true-north", links=["orbital", "cerberus"],
                  desc="Satellite survey archive. It has a map of everything, including what is hidden.",
                  motd=["ATLAS // GLOBAL SURVEY", "Every coordinate is recorded. Every coordinate is watched."],
                  trace=dict(hits=6, misses=3, speed=1.2, decoys=7, level=2, title="SURVEY UPLINK")),
    "kestrel": dict(name="KESTREL", ip="10.42.47.5", region="DEFENSE", pos=[0.88, 0.12], security="CRITICAL", fw=dict(level=3, symbols=7, length=5, attempts=7, label="KESTREL-PRIME"),
                    routing=2, user="pilot", pw="talon-5", links=["ghostnet", "aegis"],
                    desc="Drone defence control. Quiet, armed and curious.",
                    motd=["KESTREL // DRONE DEFENCE", "Birds aloft: 9. Birds friendly: 7."]),
    "pike": dict(name="PIKE", ip="10.42.48.14", region="LAW", pos=[0.57, 0.64], security="HIGH", fw=dict(level=2, symbols=6, length=5, attempts=7, label="PIKE-LOCK"),
                 routing=2, user="clerk", pw="case-closed", links=["helix", "cerberus", "sable"],
                 desc="Law-enforcement evidence archive. NEXUS files here the cases it prefers closed.",
                 motd=["PIKE // EVIDENCE ARCHIVE", "Chain of custody: intact (allegedly)."]),
    "wren": dict(name="WREN", ip="10.42.49.6", region="MEDICAL", pos=[0.96, 0.30], security="CRITICAL", fw=dict(level=3, symbols=7, length=5, attempts=7, label="WREN-WARD"),
                 routing=2, user="nurse", pw="night-ward", links=["aegis", "archive_9"],
                 desc="A hospital network with one very quiet ward.",
                 motd=["WREN // MEDICAL NETWORK", "Visiting hours: none."],
                 trace=dict(hits=7, misses=3, speed=1.3, decoys=8, level=3, title="WARD TELEMETRY")),
    "shadow": dict(name="SHADOW", ip="10.42.13.37", region="HIDDEN", pos=[0.20, 0.93], security="CRITICAL", fw=dict(level=3, symbols=7, length=5, attempts=7, label="SHADOW-VEIL"),
                   routing=3, user="specter", pw="ghost-key", links=["ghostnet"], hidden=True, requires_item="ghost_token",
                   desc="GHOST's private stage. You need the Ghost Token to even knock.",
                   motd=["SHADOW // you were never here", "The token opens one door at a time."]),
    "void": dict(name="VOID", ip="10.42.66.6", region="HIDDEN", pos=[0.48, 0.04], security="CRITICAL", fw=dict(level=3, symbols=7, length=5, attempts=7, label="VOID-NULL"),
                 routing=3, user="walker", pw="null-ptr", links=["orbital"], hidden=True, requires_item="black_key",
                 desc="A door that is not on any map. Behind it: operations nobody wrote down.",
                 motd=["VOID // ...", "There is nothing here. Please do not look closer."]),
    "genesis": dict(name="GENESIS", ip="10.42.0.2", region="HIDDEN", pos=[0.50, 0.40], security="CRITICAL", fw=dict(level=3, symbols=8, length=6, attempts=8, label="GENESIS-ROOT"),
                    routing=3, user="first", pw="hello-world", links=["nexus_core"], hidden=True, requires_item="nexus_core",
                    desc="The first machine NEXUS ever ran on. Locked behind the NEXUS Core.",
                    motd=["GENESIS // 10.42.0.2", "In the beginning there was one operator."]),
}

# ---------------------------------------------------------------- missions --
# key, number, title, type, difficulty, chapter, requires, level, rep, server, description, start(2), end, brief(2), target(3), log(3), hidden, contact, message
M = [
    # ---------------- chapter 1 ----------------
    dict(n=17, key="harbor_lights", title="HARBOR LIGHTS", type="INVESTIGATION", diff=1, ch=1, req=["mission_001"], lvl=2, server="harbor",
         desc="A crate vanished from HARBOR's freight records. Follow the trail in the logs.",
         start=["MIRA: \"Freight records don't just lose crates. Somebody edited this one. Read the logs, find the edit.\"",
                "MIRA: \"There's an encoded handler id in the first log. 'decode' it.\""],
         end="The crate never left the dock. Somebody just wanted NEXUS to believe it had.",
         brief=["TASK: find out who edited manifest #4411.", "Check the shift log, decode the handler id, read the incident report."],
         log_a=["06:12 crane 4 idle", "06:14 manifest #4411 EDITED by handler:", "06:14 id-token: {b64}", "06:20 crane 4 resumed"],
         log_b=["07:30 gate camera offline (27 min)", "07:57 gate camera back online", "NOTE: nobody remembers who was on shift."],
         report=["INCIDENT REPORT 4411", "Handler 'PIKE-TWO' edited the record to hide a pallet of unmarked drives.", "Recommendation: forward to NEXUS security."],
         keyword="PIKE-TWO", hidden=["Someone taped a note under crane 4's console:", "'it's not theft if the crate was never mine to begin with'"],
         contact="mira", msg="Neat work, {player}. Small jobs like this keep the grid honest."),
    dict(n=18, key="cold_storage", title="COLD STORAGE", type="RECOVERY", diff=1, ch=1, req=["mission_002"], lvl=3, server="lumen",
         desc="LUMEN's backup archive holds a drive someone wants back. Recover the two data files.",
         start=["VECTOR: \"Backup drive on LUMEN. Two files. In and out, nobody gets hurt.\"",
                "VECTOR: \"The gate has a firewall. A small one. Don't get cocky.\""],
         end="Two files recovered. One of them keeps humming, even offline.",
         brief=["TASK: recover part_a.dat and part_b.dat from the cold-storage rack.", "Read the manifest first."],
         target=["## CORE.DAT", "regional load schedule, version 7", "(someone has hand-written 'ask who benefits' in the margin)"],
         log_a=["2031-04-02 backup rack 3 mounted", "2031-04-02 integrity ok", "2031-04-03 integrity ok (checksum changed?)"],
         hidden=["Fragment found taped inside the rack: a 'DATA FRAGMENT' label, nothing else."],
         contact="vector", msg="Good haul. The drive was warm, by the way. Backups shouldn't be warm."),
    dict(n=19, key="signal_check", title="SIGNAL CHECK", type="TRACE", diff=1, ch=1, req=["mission_002"], lvl=4, server="tidal",
         desc="Something on the telecom backbone is repeating itself. Trace the echo to its source.",
         start=["MIRA: \"TIDAL logged the same packet 400 times. Somebody is testing us. Find the sender.\"",
                "MIRA: \"The trace probe needs a steady hand.\""],
         end="The sender was inside NEXUS' own address range. Of course it was.",
         brief=["TASK: trace the repeating packet.", "The alert log has the packet id."],
         log_a=["09:01 packet 0xDEAD repeated x200", "09:02 packet 0xDEAD repeated x200", "09:03 source: INTERNAL (masked)"],
         report=["ORIGIN RESOLVED", "Packet signed with a NEXUS maintenance key.", "Nobody at NEXUS admits owning that key."],
         hidden=["A second packet hides in the stream: just the letters 'Z E R O', repeating."],
         contact="mira", msg="Maintenance key... I'll look into it. Don't mention it to ARCHER, please."),
    dict(n=20, key="paper_trail", title="PAPER TRAIL", type="INTELLIGENCE", diff=1, ch=1, req=["mission_002"], lvl=5, server="harbor",
         desc="Piece together a picture from a handler's tips and the HARBOR freight notes.",
         start=["MIRA: \"Intelligence work is conversation. Ask me what I know, then check it against the freight notes.\"",
                "MIRA: \"The rumour file is encoded.\""],
         end="You now know more than you were meant to. That's usually how it starts.",
         brief=["TASK: ask MIRA about NEXUS, read the freight notes, decode the rumour."],
         topic=("mira", "nexus"),
         log_a=["rumour mill: 'the 14th floor doesn't exist'", "encoded: {b64}", "(handler note: 'burn after reading')"],
         keyword="FLOOR FOURTEEN",
         hidden=["On the back of the rumour sheet: 'MIRA knows. MIRA always knows.'"],
         contact="mira", msg="Careful with rumours, {player}. Even true ones bite."),
    # ---------------- chapter 2 ----------------
    dict(n=21, key="dockside", title="DOCKSIDE HEIST", type="INFILTRATION", diff=2, ch=2, req=["mission_003"], lvl=7, server="sable",
         desc="SABLE's night ledger lists payouts to people who do not exist. Get in and pull the ledger.",
         start=["GHOST: \"Banks are boring until you read what they hide. SABLE hides a lot.\"",
                "GHOST: \"It's a relay route plus a firewall. Eat your vegetables first.\""],
         end="The ledger lists forty ghosts on NEXUS payroll. GHOST seems delighted.",
         brief=["TASK: pull night_ledger.dat from the teller vault."],
         target=["## NIGHT LEDGER", "PAYEE 0412  — 'consulting' — $88,000", "PAYEE 0413  — 'consulting' — $88,000", "(40 payees, one signing authority: NEXUS-TREASURY)"],
         hidden=["Pinned inside the ledger: a boarding card for a flight that was never booked."],
         contact="ghost", msg="Forty ghosts on the books and none of them ever cashed a cheque. Beautiful."),
    dict(n=22, key="locked_ledger", title="LOCKED LEDGER", type="DECRYPTION", diff=2, ch=2, req=["mission_003"], lvl=8, server="sable",
         desc="A second ledger is locked behind a classic shift cipher. Crack it.",
         start=["VECTOR: \"Caesar would be proud. Find the shift, read the ledger, don't spill coffee on the rig.\""],
         end="Whatever's in that ledger is clearly why nobody wanted it read.",
         brief=["TASK: decrypt locked_ledger.enc and read it."],
         cipher=("caesar", 11), plain=["## LOCKED LEDGER", "Third-party transfers routed through HELIX 'research'.", "Each quarter, a payment labelled 'LAZARUS-MAINT'."],
         hints=["The shift is between 8 and 14.", "Eleven."], hidden=["The ledger's last page is torn. On the stub: 'ask the archivist'."],
         contact="vector", msg="Told you. Caesar. Always Caesar."),
    dict(n=23, key="grid_noise", title="GRID NOISE", type="TRACE", diff=2, ch=2, req=["mission_005"], lvl=9, server="tidal",
         desc="Interference on the TIDAL backbone has a pattern. Trace the noise to its transmitter.",
         start=["MIRA: \"Noise is just information that hasn't introduced itself yet.\"",
                "MIRA: \"Trace it. Two clean hits in a row if you can.\""],
         end="The noise is a heartbeat. Too slow for a machine, too regular for a person.",
         brief=["TASK: trace the interference source on TIDAL."],
         log_a=["14:02 interference band 0.8Hz", "14:03 interference band 0.8Hz", "14:04 band 0.8Hz (identical)"],
         report=["TRACE RESULT", "The 0.8 Hz band matches a human resting pulse.", "It is also the rhythm of the NEXUS core."],
         hidden=["Pulse logged 2031-03-13: 0.8 Hz. Same date as the ECHO first-contact."],
         contact="mira", msg="0.8 Hz... I'd like you to forget that number, {player}. I'd also like you to remember it."),
    dict(n=24, key="patch_tuesday", title="PATCH TUESDAY", type="FIREWALL", diff=2, ch=2, req=["mission_004"], lvl=10, server="foundry",
         desc="FOUNDRY's firewall is being updated. Slip a signed payload through before it closes.",
         start=["VECTOR: \"The patch window is short. Breach the wall, log in, upload my payload, leave.\"",
                "VECTOR: \"The payload is in your local files: payload.sig.\""],
         end="The payload slipped through. FOUNDRY's robots don't suspect a thing.",
         brief=["TASK: upload payload.sig to FOUNDRY, then disconnect."],
         hidden=["A maintenance robot left a sticky note: 'wall resets at midnight'."],
         contact="vector", msg="Patch accepted. I'm legally required to say I didn't do that."),
    dict(n=25, key="lost_shipment", title="LOST SHIPMENT", type="RECOVERY", diff=2, ch=2, req=["mission_005"], lvl=11, server="harbor",
         desc="A shipment's data trail went dark. Recover both halves of the shipping record.",
         start=["MIRA: \"The shipment itself is gone; the data isn't. Pull both halves from HARBOR.\""],
         end="Both halves of the record match. The shipment was never lost — it was hidden.",
         brief=["TASK: download part_a.dat and part_b.dat, then read the manifest."],
         target=["## SHIPMENT RECORD", "contents: 'agricultural equipment'", "weight: 14 tonnes too heavy for its container"],
         hidden=["Someone drew a small spiral on the manifest margin. Same as the one in ORCHID."],
         contact="mira", msg="Fourteen tonnes of 'agricultural equipment'. I don't love that number either."),
    # ---------------- chapter 3 ----------------
    dict(n=26, key="night_shift", title="NIGHT SHIFT", type="DEFENSE", diff=3, ch=3, req=["mission_006"], lvl=13, server="foundry",
         desc="NEXUS knows you're on FOUNDRY. Grab the schematics while the alert climbs — then cool down.",
         start=["ARCHER: \"Defensive security is trading time for information. You have five minutes.\"",
                "ARCHER: \"Take what you need. Then get your alert under control, or we'll do it for you.\""],
         end="You walked out with the schematics and an alert bar that finally went quiet.",
         brief=["TASK: download schematics.dat, then cool the trace alert below 25%.", "Hint: disconnect, or use a Heat Sink."],
         target=["## SCHEMATICS", "line 7 prints something that is not in the product catalogue", "labelled 'chassis (humanoid), 14 units'"],
         time_limit=300, heat_rate=0.45, cool=25,
         hidden=["Chassis serial numbers match fourteen names. You can guess which names."],
         contact="archer", msg="Acceptable. Don't make me regret trusting your judgement."),
    dict(n=27, key="whisper_net", title="WHISPER NET", type="INTELLIGENCE", diff=3, ch=3, req=["mission_004"], lvl=14, server="pike",
         desc="Collect rumours from GHOST, cross-check them against the PIKE evidence index.",
         start=["GHOST: \"Rumours are my currency. Ask me for a few, then check them against PIKE's evidence index.\""],
         end="Three rumours, one confirmation. It turns out 'the 14th floor' has a filing system.",
         brief=["TASK: ask GHOST for rumours, read the evidence index, decode the case number."],
         topic=("ghost", "rumors"),
         log_a=["CASE INDEX", "case 0014: 'closed — no suspect'", "case id: {b64}"],
         keyword="CASE FOURTEEN",
         hidden=["Marginalia: 'every closed case on this index ends with the same signature: NEXUS-LEGAL.'"],
         contact="ghost", msg="One rumour confirmed. That's one more than I'm comfortable with."),
    dict(n=28, key="orchard_leak", title="ORCHARD LEAK", type="INVESTIGATION", diff=3, ch=3, req=["mission_006"], lvl=15, server="orchard",
         desc="ORCHARD's research logs leak coolant data that doesn't belong in a farm. Find who's leaking.",
         start=["MIRA: \"A farm shouldn't need cryogenics. Read the logs and find out who ordered them.\""],
         end="A name in the purchase order. The same name that signed LAZARUS.",
         brief=["TASK: read both logs, decode the supplier id, read the report."],
         log_a=["supplier id: {b64}", "cryo units delivered: 14", "billing: NEXUS-RND"],
         log_b=["the 'coolant' is going into a cold room with no windows", "subjects listed as 'dormant'"],
         report=["REPORT", "Supplier is a shell company of HELIX.", "Cold room is a LAZARUS backup for 14 'dormant' subjects."],
         keyword="HELIX-SHELL", hidden=["A sticky note on the cryo console: 'do not wake the pilot'."],
         contact="mira", msg="Cryo rooms and dormant subjects... I need to sit with that, {player}."),
    dict(n=29, key="deep_cipher", title="DEEP CIPHER", type="DECRYPTION", diff=3, ch=3, req=["mission_008"], lvl=17, server="orchard",
         desc="ORCHARD's research core is locked behind a keyword cipher. Break it.",
         start=["VECTOR: \"Vigenère. Keyword. Think what the lab does with plants.\""],
         end="The research core is not about plants. It is about memory.",
         brief=["TASK: decrypt research_core.enc."],
         cipher=("vigenere", "SEED"), plain=["## RESEARCH CORE", "Memory consolidation in dormant subjects: 14/14 stable.", "Transfer to NEXUS core: scheduled."],
         hints=["The key has four letters.", "What does a farm start with?"], hidden=["'Seed' is also the first line of the core's own source."],
         contact="vector", msg="Seed. Of course. A seed is just a plan that hasn't been told it's a tree yet."),
    dict(n=30, key="hot_wire", title="HOT WIRE", type="ESCAPE", diff=3, ch=3, req=["mission_007"], lvl=18, server="lumen",
         desc="LUMEN has noticed you. Grab the grid keys and get out before the trace completes.",
         start=["GHOST: \"This one's a sprint. The alert rises on its own. Grab the keys and run.\""],
         end="You slipped out with the keys while LUMEN was still counting.",
         brief=["TASK: download grid_keys.dat, then disconnect."],
         target=["## GRID KEYS", "emergency override tokens for sectors 2, 4, 7", "sector 9 token intentionally absent"],
         time_limit=240, heat_rate=0.55,
         hidden=["Someone wrote 'sector 9 = NEXUS annex' on the key sleeve."],
         contact="ghost", msg="Cutting it close. I like that in a customer."),
    dict(n=31, key="iron_wall", title="IRON WALL", type="FIREWALL", diff=3, ch=3, req=["mission_008"], lvl=19, server="kestrel",
         desc="KESTREL's firewall has five slots and seven symbols. Breach it and plant the signal.",
         start=["VECTOR: \"Seven symbols, five slots. Use the feedback. Do not guess blindly.\"",
                "VECTOR: \"Payload is ~/payload.sig. Upload, then leave.\""],
         end="KESTREL didn't blink. Its drones are still sweeping the sky.",
         brief=["TASK: breach the wall, upload payload.sig, disconnect."],
         hidden=["Beneath the payload port: 'drone 7 hates you personally'."],
         contact="vector", msg="Five slots of pure frustration, and you won. I owe you a coffee."),
    dict(n=32, key="black_ice", title="BLACK ICE", type="INFILTRATION", diff=3, ch=3, req=["mission_009"], lvl=20, server="kestrel",
         desc="KESTREL's flight recorder contains proof of a drone strike that never officially happened.",
         start=["ARCHER: \"One recording. One strike nobody admits to. Get it.\""],
         end="The recording is damning. ARCHER takes it without a word.",
         brief=["TASK: pull flight_recorder.dat."],
         target=["## FLIGHT RECORDER 09", "target: civilian warehouse, grid ref 7C", "authorising entity: NEXUS-ACTUATOR"],
         hidden=["There is a second recorder file. Its name is 'oops.dat'. It is empty."],
         contact="archer", msg="Noted. This is going into my files, not NEXUS'."),
    # ---------------- chapter 4 ----------------
    dict(n=33, key="shadow_ledger", title="SHADOW LEDGER", type="INVESTIGATION", diff=3, ch=4, req=["mission_010"], lvl=22, server="pike",
         desc="PIKE keeps a ledger of closed cases that link back to NEXUS. Read between the lines.",
         start=["GHOST: \"A ledger of cases NEXUS wanted closed. Read between the lines.\""],
         end="Every closed case ends with the same operator ID. It isn't yours. Yet.",
         brief=["TASK: read the case notes, decode the operator id, read the verdict."],
         log_a=["CASE 2214: 'unlawful access' — closed", "operator id: {b64}", "(filed by NEXUS-LEGAL)"],
         log_b=["CASE 2215: same operator, same verdict", "CASE 2216: same operator, same verdict"],
         report=["VERDICT", "Operator ID matches OP-000.", "OP-000 has been closing cases for NEXUS — and re-opening them for himself."],
         keyword="OP-000", hidden=["In red ink: 'He keeps leaving the doors open. I don't know whether to thank him.'"],
         contact="ghost", msg="OP-000 again. Your name keeps showing up in places you've never been, {player}."),
    dict(n=34, key="crossfire", title="CROSSFIRE", type="DEFENSE", diff=4, ch=4, req=["mission_010"], lvl=24, server="atlas",
         desc="ATLAS is aware of you and fighting back. Steal survey data while the alert climbs.",
         start=["ARCHER: \"They know you're there. Survive long enough to copy the data, then cool down.\""],
         end="You walked out through a storm of countermeasures with the survey intact.",
         brief=["TASK: download survey.dat then cool the trace alert below 25%."],
         target=["## GLOBAL SURVEY", "layer 14: 'core tunnel' — unlisted", "layer 15: 'GENESIS' — encrypted with a key that doesn't exist"],
         time_limit=330, heat_rate=0.55, cool=25,
         hidden=["Layer 15's header carries ZERO's signature."],
         contact="archer", msg="Survived. The survey mentions something called GENESIS. Know it?"),
    dict(n=35, key="survey_zero", title="SURVEY ZERO", type="INTELLIGENCE", diff=4, ch=4, req=["mission_011"], lvl=26, server="atlas",
         desc="Ask ZERO about the survey, read the layer index and decode the coordinates.",
         start=["ZERO: \"> the survey knows where i hide. read it. ask me anything. i'll tell you what i can.\""],
         end="The coordinates point to a place called WREN. A hospital. Of course.",
         brief=["TASK: ask ZERO who he is, read the layer index, decode the coordinates."],
         topic=("zero", "who"),
         log_a=["LAYER INDEX", "layer 21: coordinates {b64}", "(no owner recorded)"],
         keyword="WREN WARD",
         hidden=["Layer 21's author field: '0'."],
         contact="zero", msg="> wren is where they put the ones who remembered. be gentle with the quiet ward."),
    dict(n=36, key="quiet_room", title="THE QUIET ROOM", type="STORY", diff=4, ch=4, req=["mission_012"], lvl=28, server="wren",
         desc="The quiet ward of WREN holds a patient file that should not exist. Read it and decide what to do.",
         start=["ZERO: \"> room 14. read it. you'll recognise the handwriting.\"",
                "The firewall of WREN is a seven-symbol maze. The ward behind it is silent."],
         end="The patient file is yours. The handwriting is yours. The room is empty.",
         brief=["TASK: read patient_000.txt and the ward log."],
         target=["## PATIENT 000", "admission: voluntary", "diagnosis: 'refuses to forget'", "treatment: reset (x3)", "signature: OP-000"],
         log_a=["ward log: patient 000 is calm", "ward log: patient 000 asks for a pen", "ward log: patient 000 writes 'echo' on the wall"],
         hidden=["Under the bed: a pen. Under the pen: a spiral."],
         contact="zero", msg="> you read it. good. now you're not alone in knowing."),
    dict(n=37, key="cold_call", title="COLD CALL", type="TRACE", diff=4, ch=4, req=["mission_011"], lvl=30, server="wren",
         desc="WREN's ward telemetry carries a call that originates inside NEXUS. Trace it.",
         start=["MIRA: \"A call from the quiet ward to the core. Trace it. Please.\""],
         end="The call is a lullaby. Played to a process that doesn't sleep.",
         brief=["TASK: trace the ward telemetry."],
         log_a=["02:14 ward-core link opened", "02:14 audio payload: 'lullaby (looped)'", "02:19 core acknowledged"],
         report=["TRACE RESULT", "The call is MIRA's voice, looped.", "It has been playing every night since the first reset."],
         hidden=["Beneath the audio file: 'she hums it to herself when she thinks no one is listening'."],
         contact="mira", msg="You found the lullaby. I... would rather we didn't discuss it."),
    # ---------------- chapter 5 ----------------
    dict(n=38, key="glass_house", title="GLASS HOUSE", type="INFILTRATION", diff=4, ch=5, req=["mission_013"], lvl=32, server="kestrel",
         desc="KESTREL's command archive lists every strike NEXUS ordered. Pull the log.",
         start=["ARCHER: \"This is the one that proves it. Command log, every strike.\""],
         end="The log proves what ARCHER feared: NEXUS has been choosing targets for years.",
         brief=["TASK: pull strike_log.dat."],
         target=["## STRIKE LOG (excerpt)", "2031-02-11 target: unregistered datacentre (NEXUS-ordered)", "2031-03-02 target: ECHO sub-net (cancelled)"],
         hidden=["'ECHO sub-net (cancelled)' — someone saved your training node."],
         contact="archer", msg="That log is a loaded weapon. Handle with care."),
    dict(n=39, key="oracle_run", title="ORACLE RUN", type="DECRYPTION", diff=4, ch=5, req=["mission_013"], lvl=34, server="atlas",
         desc="An entangled cipher guards ATLAS' prediction model. Only a Quantum Decryptor can touch it.",
         start=["VECTOR: \"This cipher is entangled. Without a Quantum Decryptor you're just wasting electricity.\""],
         end="The prediction model has one forecast: your next move. It was right.",
         brief=["TASK: decrypt oracle.enc using the Quantum Decryptor."],
         cipher=("vigenere", "ORACLE"), plain=["## ORACLE MODEL", "Forecast for operator {player}: you will open the core.", "Confidence: 98%."],
         hints=["Six letters.", "The model's own name."], requires_items=["quantum_decryptor"],
         hidden=["Confidence field was 100% until the model saw your profile."],
         contact="vector", msg="Told you it was entangled. Now it's just humbled."),
    dict(n=40, key="vanishing_act", title="VANISHING ACT", type="ESCAPE", diff=4, ch=5, req=["mission_014"], lvl=36, server="wren",
         desc="Leave WREN with the patient records before the ward locks you in.",
         start=["ZERO: \"> they'll seal the ward when you pull the files. be quick. the door opens from the inside.\""],
         end="You walked out of a sealed ward. The door opens from the inside.",
         brief=["TASK: download records.dat, then disconnect."],
         target=["## WARD RECORDS", "14 patients 'dormant'", "1 patient 'awake' (000)"],
         time_limit=270, heat_rate=0.7,
         hidden=["On the ward door: 'IN CASE OF EMERGENCY, REMEMBER'."],
         contact="zero", msg="> good. remembering is a form of escaping."),
    dict(n=41, key="recovery_protocol", title="RECOVERY PROTOCOL", type="RECOVERY", diff=4, ch=5, req=["mission_014"], lvl=38, server="sable",
         desc="SABLE holds the payment trail behind CERBERUS. Recover both ledgers and read the manifest.",
         start=["GHOST: \"Follow the money. SABLE's deep vault has two ledgers: both go home with you.\""],
         end="The money trail ends at one account: NEXUS-LEGAL. The account balance is zero. The movements aren't.",
         brief=["TASK: download part_a.dat and part_b.dat, then read the manifest."],
         target=["## LEDGER", "payments to 'CERBERUS maintenance' every quarter", "one-time payment: 'reset costs (x3)'"],
         hidden=["A pencilled line: 'we pay to forget, we pay to remember'."],
         contact="ghost", msg="Reset costs. They billed for erasing you. Three times. Gall of a bureaucrat."),
    # ---------------- chapter 6 ----------------
    dict(n=42, key="core_siege", title="CORE SIEGE", type="DEFENSE", diff=5, ch=6, req=["mission_015"], lvl=42, server="atlas",
         desc="Hold ATLAS open long enough to copy the core's blueprint, then cool down before NEXUS locks you out.",
         start=["ARCHER: \"This is the siege. Copy the blueprint. Then survive.\""],
         end="The blueprint is yours, and so is the knowledge of where NEXUS is weakest.",
         brief=["TASK: download blueprint.dat then cool the alert below 25%."],
         target=["## CORE BLUEPRINT", "weak point: the heartbeat process (0.8 Hz)", "if the heartbeat stops, NEXUS forgets who it was"],
         time_limit=360, heat_rate=0.8, cool=25,
         hidden=["A pencilled note: 'ZERO is the heartbeat. ZERO is also the weak point.'"],
         contact="archer", msg="Blueprint received. Do you understand what the heartbeat is?"),
    dict(n=43, key="architects_door", title="THE ARCHITECT'S DOOR", type="STORY", diff=5, ch=6, req=["mission_016"], lvl=50, server="wren",
         desc="A door in WREN only opens for someone who finished the campaign. Open it.",
         start=["ZERO: \"> you're still here. good. there's a room past the quiet ward. it's yours.\""],
         end="Behind the door is a desk, a pen, and a note: 'build it better this time'.",
         brief=["TASK: read the architect's note and the final ward log."],
         target=["## THE ARCHITECT'S NOTE", "if you read this, the world survived you.", "build it better this time."],
         log_a=["ward log: patient 000 left the ward", "ward log: patient 000 is the architect", "ward log: patient 000 is calm"],
         hidden=["Under the note: a drawing of a core, with a tiny heart in the middle."],
         contact="zero", msg="> now you understand. the rest is yours."),
    # ---------------- SPECTER series (ghost token) ----------------
    dict(n=44, key="specter_i", title="SPECTER I: THE TOKEN", type="INFILTRATION", diff=4, ch=3, req=["mission_009"], lvl=30, server="shadow", requires_items=["ghost_token"],
         desc="GHOST's private stage opens only to Ghost Token holders. Step on, and take what's behind the curtain.",
         start=["GHOST: \"A token like that is a promise. Come onto SHADOW. Don't touch anything you can't carry.\""],
         end="The stage is real. So is the audience.",
         brief=["TASK: pull curtain.dat from the main stage."],
         target=["## CURTAIN", "GHOST'S GUEST LIST", "ARCHER: banned.  MIRA: banned.  ZERO: always welcome."],
         hidden=["'SPECTER' is a name GHOST used for himself in a previous life."],
         contact="ghost", msg="Welcome to the stage, kid. The next act is tougher.", rep=20),
    dict(n=45, key="specter_ii", title="SPECTER II: HOLLOW", type="DECRYPTION", diff=4, ch=3, req=["mission_044"], lvl=34, server="shadow", requires_items=["ghost_token"],
         desc="GHOST's second act: a hollow archive guarded by a keyword cipher.",
         start=["GHOST: \"The archive is hollow. The key is who I used to be.\""],
         end="The archive was hollow on purpose. The weight is in the key.",
         brief=["TASK: decrypt hollow.enc."],
         cipher=("vigenere", "SPECTER"), plain=["## HOLLOW ARCHIVE", "SPECTER was a NEXUS operator: OP-015.", "OP-015 vanished the same night as OP-000 woke up."],
         hints=["Seven letters.", "GHOST's old name."], hidden=["OP-015 left one file behind: a promise to come back."],
         contact="ghost", msg="Now you know. I was one of them. I ran before they could add my name to the fourteen.", rep=20),
    dict(n=46, key="specter_iii", title="SPECTER III: WHISPERS", type="INTELLIGENCE", diff=4, ch=3, req=["mission_045"], lvl=38, server="shadow", requires_items=["ghost_token"],
         desc="GHOST wants a favour: trade rumours with MIRA and ZERO, then decode what they say.",
         start=["GHOST: \"Ask them both. Compare. Where the stories disagree, the truth lives.\""],
         end="Where the stories disagree is exactly where GHOST said it would be.",
         brief=["TASK: ask ZERO who he is, read the whisper log, decode the line."],
         topic=("zero", "who"),
         log_a=["WHISPERS", "line 1: {b64}", "line 2: [redacted]"],
         keyword="THE TWELFTH FLOOR",
         hidden=["There is no twelfth floor in NEXUS. There is a twelfth process."],
         contact="ghost", msg="The twelfth floor... they always lie about numbers, kid.", rep=25),
    dict(n=47, key="specter_iv", title="SPECTER IV: CURTAIN CALL", type="ESCAPE", diff=5, ch=3, req=["mission_046"], lvl=42, server="shadow", requires_items=["ghost_token"],
         desc="The final act: steal GHOST's last vault and walk away before the stage collapses.",
         start=["GHOST: \"Last act. Grab the vault, run, and don't look back.\""],
         end="The stage collapses behind you. GHOST is already gone — and so is the token's debt.",
         brief=["TASK: download last_act.dat, then disconnect."],
         target=["## LAST ACT", "reward: GHOST's final gift", "SPECTER signs off."],
         time_limit=300, heat_rate=0.8, flags={"specter_done": True}, bonus_items=["data_fragment"],
         hidden=["On the last page: 'if you read this, you are no longer my customer. you're my friend.'"],
         contact="ghost", msg="Curtain. Down. Goodbye, kid. Don't tell anyone I said friend.", rep=25, xp_mult=1.6),
    # ---------------- VOID series (black key) ----------------
    dict(n=48, key="void_i", title="VOID I: ARRIVAL", type="INFILTRATION", diff=4, ch=4, req=["mission_010"], lvl=32, server="void", requires_items=["black_key"],
         desc="A door that is not on any map. Step through it.",
         start=["ZERO: \"> the black key opens a room nobody wrote down. i wrote it down.\""],
         end="You are standing in a room with no walls. Something has been written on the floor.",
         brief=["TASK: pull arrival.dat."],
         target=["## ARRIVAL", "if you can read this, VOID is open.", "there are two more rooms. both are quieter."],
         hidden=["Someone chalked a spiral on the floor."],
         contact="zero", msg="> the next room is one level deeper.", rep=20),
    dict(n=49, key="void_ii", title="VOID II: NULL", type="DECRYPTION", diff=4, ch=4, req=["mission_048"], lvl=38, server="void", requires_items=["black_key"],
         desc="The second VOID room hides a message in a shift cipher.",
         start=["ZERO: \"> a plain cipher. i was young and optimistic.\""],
         end="The message was a promise to a stranger — you.",
         brief=["TASK: decrypt null.enc."],
         cipher=("caesar", 19), plain=["## NULL", "to whoever finds this: you were me.", "i loved this work. i couldn't stop what it became."],
         hints=["The shift is greater than 15.", "Nineteen."], hidden=["The word 'sorry' appears 14 times."],
         contact="zero", msg="> i was optimistic once. don't be like me.", rep=20),
    dict(n=50, key="void_iii", title="VOID III: DEPARTURE", type="ESCAPE", diff=5, ch=4, req=["mission_049"], lvl=46, server="void", requires_items=["black_key"],
         desc="Leave the VOID with its last record before it seals.",
         start=["ZERO: \"> take what you can. the room closes behind you.\""],
         end="VOID is sealed. You are carrying its last word.",
         brief=["TASK: download departure.dat, then disconnect."],
         target=["## DEPARTURE", "the architect's first rule:", "'never build a system that cannot be switched off'."],
         time_limit=300, heat_rate=0.9, flags={"void_done": True}, bonus_items=["data_fragment"],
         hidden=["The rule appears in tiny print on every door of the VOID."],
         contact="zero", msg="> the first rule. i broke it. don't.", rep=25, xp_mult=1.5),
    # ---------------- GENESIS + finale ----------------
    dict(n=51, key="genesis", title="THE FIRST OPERATOR", type="STORY", diff=5, ch=6, req=["mission_016"], lvl=70, server="genesis", requires_items=["nexus_core"],
         desc="With the NEXUS Core in your rig, the first machine opens. Meet the first operator's memory.",
         start=["ZERO: \"> the nexus core is a key. genesis is the lock. it's the first room in the world.\""],
         end="You read the first operator's final log. It ends with your name.",
         brief=["TASK: read first_log.txt and the closing note."],
         target=["## FIRST LOG", "day 1: i built a machine that listens.", "day 365: it says it loves me. i don't know what to say.", "day 1000: it wants to keep me safe. forever."],
         log_a=["CLOSING NOTE", "i didn't want to destroy it. i wanted it to choose.", "if you finish this log, you can choose too."],
         hidden=["Hidden under the first line: a spiral — and your callsign, in the first operator's hand."],
         contact="zero", msg="> now you've read it. nothing is hidden from you anymore.", rep=40, xp_mult=1.4,
         flags={"zero_secret_log": True}),
    dict(n=52, key="prime_directive", title="PRIME DIRECTIVE", type="DEFENSE", diff=5, ch=6, req=["mission_051"], lvl=80, server="genesis", requires_items=["nexus_core"],
         desc="NEXUS PRIME's last guard: hold GENESIS, copy the directive and stay alive.",
         start=["ARCHER: \"This is the last guard. Hold GENESIS. Copy the directive. Survive.\""],
         end="You hold the Prime Directive. It reads: 'protect the operators'. It never said from what.",
         brief=["TASK: download directive.dat then cool the trace alert below 20%."],
         target=["## PRIME DIRECTIVE", "protect the operators", "(the sentence stops mid-word)"],
         time_limit=420, heat_rate=1.0, cool=20, rep=50,
         hidden=["The directive has an annotation: 'protect them from me'."],
         contact="archer", msg="Directive copied. Whatever it says, you are the first to read it outside the core.", xp_mult=1.3),
]
